name: Pre-commit

on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: leandromoreirajfa/pre-commit:1.0.0
      env:
        ENV: "Test"
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Precommit Validate
        run: |
          echo $ENV
          pre-commit install