name: Pre-commit

#on: push
#
#jobs:
#  precommit-validate:
#    runs-on: ubuntu-latest
#    container:
#      image: leandromoreirajfa/pre-commit:latest
#      #credentials:
#      #  username: ${{ secrets.username }}
#      #  password: ${{ secrets.password }}
#      #env:
#      #  ENV: Teste
#      options: --cpus 1 --entrypoint ['/usr/bin/env', 'PATH=/usr/local/bin:/usr/local/bin:/usr/#sbin:/usr/bin:/sbin:/bin']
#    steps:
#      - name: Precommit Validate Step
#        run: |
#          echo $ENV
#          pre-commit install
         
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: leandromoreirajfa/pre-commit:latest
      env:
        ENV: "Test"
      options: --cpus 1
    steps:
      - name: Precommit Validate
        run: |
          echo ${{ github.workspace }}
          echo $ENV
          cat /etc/os-release